baseURL = 'https://xeyusarchive.onrender.com'
languageCode = 'zh-CN'
title = 'Xeyus Archive'
theme = 'PaperMod'

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series" # 开启系列文章功能

[permalinks]
    literature = "/lit/:contentbasename/"
    review  = "/review/:contentbasename/"
    essay   = "/essays/:contentbasename/"
    cut    = "/cut/:contentbasename/"
    log      = "/log/:contentbasename/"
    wiki     = "/wiki/:contentbasename/"

[menu]
    # 顶部导航栏配置
    [[menu.main]]
        identifier = "literature"
        name = "创作"
        url = "/lit/"
        weight = 10
    [[menu.main]]
        identifier = "review"
        name = "回响"
        url = "/review/"
        weight = 20
    [[menu.main]]
        identifier = "essay"
        name = "思辨"
        url = "/essay/"
        weight = 30
    [[menu.main]]
        identifier = "cut"
        name = "瞬念"
        url = "/cut/"
        weight = 40
    [[menu.main]]
        identifier = "wiki"
        name = "馆藏"
        url = "/wiki/"
        weight = 50
    [[menu.main]]
        identifier = "log"
        name = "时轴"
        url = "/log/"
        weight = 60