baseURL = 'https://geistlicht.work'
languageCode = 'zh-CN'
title = 'Xeyus Archive'
theme = 'limbus-archive-theme'
defaultContentLanguage = "zh"  # 设定中文为默认
defaultContentLanguageInSubdir = false # 关键！设为 false，则中文路径为 / 而非 /zh/

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series" # 开启系列文章功能

[permalinks]
    literature = "/lit/:contentbasename/"
    review  = "/review/:contentbasename/"
    essay   = "/essays/:contentbasename/"
    flash    = "/flash/:contentbasename/"
    log      = "/log/:contentbasename/"
    wiki     = "/wiki/:contentbasename/"

[languages]
  [languages.zh]
    languageName = "简体中文"
    contentDir = "content/zh"
    weight = 1
    title = "Xeyus Archive"

    [languages.zh.params]
    mainSections = ["literature", "essay", "review", "flash"]
    
    [[languages.zh.menu.main]]
      name = "创作"
      url = "/lit/"
      weight = 10
    [[languages.zh.menu.main]]
      name = "回响"
      url = "/review/"
      weight = 20
    [[languages.zh.menu.main]]
      name = "思辨"
      url = "/essay/"
      weight = 30
    [[languages.zh.menu.main]]
      name = "瞬念"
      url = "/flash/"
      weight = 40
    [[languages.zh.menu.main]]
      name = "馆藏"
      url = "/wiki/" 
      weight = 50
    [[languages.zh.menu.main]]
      name = "时轴"
      url = "/log/"
      weight = 60

  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 2
    title = "Xeyus Archive"

    [languages.en.params]
    mainSections = ["literature", "essay", "review", "flash"]

    [[languages.en.menu.main]]
      name = "Literature"
      url = "/lit/"
      weight = 10
    [[languages.en.menu.main]]
      name = "Review"
      url = "/review/"
      weight = 20
    [[languages.en.menu.main]]
      name = "Essay"
      url = "/essay/"
      weight = 30
    [[languages.en.menu.main]]
      name = "Flash"
      url = "/flash/"
      weight = 40
    [[languages.en.menu.main]]
      name = "Wiki"
      url = "/wiki/"
      weight = 50
    [[languages.en.menu.main]]
      name = "Log"
      url = "/log/"
      weight = 60

  [languages.de]
    languageName = "Deutsch"
    contentDir = "content/de"
    weight = 3
    title = "Xeyus Archiv"

    [languages.de.params]
    mainSections = ["literature", "essay", "review", "flash"]

    [[languages.de.menu.main]]
      name = "Literatur"
      url = "/lit/"
      weight = 10
    [[languages.de.menu.main]]
      name = "Rezension"
      url = "/review/"
      weight = 20
    [[languages.de.menu.main]]
      name = "Aufsatz"
      url = "/essay/"
      weight = 30
    [[languages.de.menu.main]]
      name = "Notizen"
      url = "/flash/"
      weight = 40
    [[languages.de.menu.main]]
      name = "Wiki"
      url = "/wiki/"
      weight = 50
    [[languages.de.menu.main]]
      name = "Protokoll"
      url = "/log/"
      weight = 60